name: Security Scanning

on:
  workflow_call:
    inputs:
      sha:
        required: false
        type: string
        default: ${{ github.sha }}

jobs:
  security:
    name: Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Detect secrets with Talisman in incoming commits
        uses: carhartl/talisman-secrets-scan-action@v1.4.0
        continue-on-error: true
