name: DevSecOps Pipeline - Main Orchestrator

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    name: Security Scanning
    uses: ./.github/workflows/security.yml

  trivy:
    name: Trivy Security Scanner
    uses: ./.github/workflows/trivy.yml
    with:
      scan-type: "fs"
      severity: "CRITICAL,HIGH,MEDIUM"
      format: "sarif"

  testing:
    name: Testing and Build
    needs: [security, trivy]
    uses: ./.github/workflows/testing.yml

  # sast:
  #   name: SAST - Static Analysis
  #   needs: testing
  #   uses: ./.github/workflows/sonarqube.yml
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker:
    name: Docker Build and Push
    needs: [testing]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      app-jar: ${{ needs.testing.outputs.app-jar }}

  k8s-security:
    name: Kubernetes Security Scan
    needs: docker
    uses: ./.github/workflows/k8s-security.yml
    with:
      manifest-directory: "kubernetes"

  deployment:
    name: Kubernetes Deployment with Rollout
    needs: [docker, k8s-security]
    uses: ./.github/workflows/deployment.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    with:
      image-tag: "devsecops:${{ github.sha }}"

  integration-tests:
    name: Integration Tests
    needs: deployment
    uses: ./.github/workflows/integration-tests.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
    with:
      service-name: "devsecops-svc"
      application-url: "http://localhost"
      application-uri: "/increment/99"

  owasp-zap:
    name: OWASP ZAP DAST Scan
    needs: integration-tests
    uses: ./.github/workflows/owasp-zap.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
    with:
      service-name: "devsecops-svc"
      application-url: "http://localhost"
      application-uri: "/v3/api-docs"

  slack-notification:
    name: Slack Notification
    needs:
      [
        security,
        trivy,
        testing,
        docker,
        k8s-security,
        deployment,
        integration-tests,
        owasp-zap,
      ]
    uses: ./.github/workflows/slack-notification.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      channel: "github-actions-channel"
      message: ":hammer_and_wrench: DevSecOps Pipeline completed"
      title: "Pipeline Status"
